services:
  - type: web
    name: django-course-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.core.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.11
